fixtures:
  repositories:
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "3.0.0"
    "shell_config": "http://tig.csail.mit.edu/git-public/shell_config.git/"
  symlinks:
    "smartd": "#{source_dir}"
