---
default_set: 'centos-64-x64'
sets:
  'centos-64-x64':
    nodes:
      'main.vm':
        prefab: 'centos-64-x64'
  'debian-607-x64':
    nodes:
      'main.vm':
        prefab: 'debian-607-x64'
  'ubuntu-server-12042-x64':
    nodes:
      "main.vm":
        prefab: 'ubuntu-server-12042-x64'
